apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: redhat-keycloak

resources:
  - 01_postgresql.yaml
  - 02_keycloak.yaml
  - 04_realm.yaml
  - clusterrolevinding.yaml
  # Note: 00_featuregate.yaml and authentication-config.yaml are applied separately
  # to openshift-config namespace, not included in kustomize build
